// <auto-generated />
using System;
using BellaHair.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BellaHair.Infrastructure.Migrations
{
    [DbContext(typeof(BellaHairDbContext))]
    [Migration("20251128150040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BellaHair.Domain.Entities.Behandling", b =>
                {
                    b.Property<int>("BehandlingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BehandlingId"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VarighedMinutter")
                        .HasColumnType("int");

                    b.HasKey("BehandlingId");

                    b.ToTable("Behandlinger");

                    b.HasData(
                        new
                        {
                            BehandlingId = 1,
                            Navn = "Standard klip",
                            Pris = 100m,
                            Type = "",
                            VarighedMinutter = 0
                        },
                        new
                        {
                            BehandlingId = 2,
                            Navn = "Herreklip",
                            Pris = 80m,
                            Type = "",
                            VarighedMinutter = 0
                        },
                        new
                        {
                            BehandlingId = 3,
                            Navn = "Farve",
                            Pris = 150m,
                            Type = "",
                            VarighedMinutter = 0
                        },
                        new
                        {
                            BehandlingId = 4,
                            Navn = "Balayage",
                            Pris = 250m,
                            Type = "",
                            VarighedMinutter = 0
                        },
                        new
                        {
                            BehandlingId = 5,
                            Navn = "Kurbehandling",
                            Pris = 60m,
                            Type = "",
                            VarighedMinutter = 0
                        });
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("BehandlingId")
                        .HasColumnType("int");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<int>("MedarbejderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValgtRabat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Varighed")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BehandlingId");

                    b.HasIndex("KundeId");

                    b.HasIndex("MedarbejderId");

                    b.ToTable("Bookinger");
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Faktura", b =>
                {
                    b.Property<int>("FakturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FakturaId"));

                    b.Property<decimal>("Beløb")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Cvr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ErFirmafaktura")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FakturaDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firmanavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RabatBeløb")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RabatTekst")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalBeløb")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FakturaId");

                    b.HasIndex("BookingId");

                    b.HasIndex("KundeId");

                    b.ToTable("Fakturaer");
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundeId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BesøgAntal")
                        .HasColumnType("int");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fødselsdag")
                        .HasColumnType("date");

                    b.Property<string>("LoyaltyTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Postnr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundeId");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            KundeId = 1,
                            Adresse = "",
                            BesøgAntal = 0,
                            By = "",
                            Email = "",
                            Fødselsdag = new DateOnly(1, 1, 1),
                            Navn = "Kendrick",
                            Points = 0,
                            Postnr = "",
                            Telefon = ""
                        },
                        new
                        {
                            KundeId = 2,
                            Adresse = "",
                            BesøgAntal = 0,
                            By = "",
                            Email = "",
                            Fødselsdag = new DateOnly(1, 1, 1),
                            Navn = "J. Cole",
                            Points = 0,
                            Postnr = "",
                            Telefon = ""
                        },
                        new
                        {
                            KundeId = 3,
                            Adresse = "",
                            BesøgAntal = 0,
                            By = "",
                            Email = "",
                            Fødselsdag = new DateOnly(1, 1, 1),
                            Navn = "Drake",
                            Points = 0,
                            Postnr = "",
                            Telefon = ""
                        });
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Medarbejder", b =>
                {
                    b.Property<int>("MedarbejderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedarbejderId"));

                    b.Property<bool>("ErFreelancer")
                        .HasColumnType("bit");

                    b.Property<string>("Kompetencer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedarbejderId");

                    b.ToTable("Medarbejdere");

                    b.HasData(
                        new
                        {
                            MedarbejderId = 1,
                            ErFreelancer = false,
                            Kompetencer = "[]",
                            Navn = "Mia"
                        },
                        new
                        {
                            MedarbejderId = 2,
                            ErFreelancer = false,
                            Kompetencer = "[]",
                            Navn = "Sara"
                        },
                        new
                        {
                            MedarbejderId = 3,
                            ErFreelancer = false,
                            Kompetencer = "[]",
                            Navn = "Jonas"
                        });
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Rabat", b =>
                {
                    b.Property<int>("RabatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RabatId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FixedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsKampagne")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinimumBeløb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RequiredLoyaltyTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SlutDato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDato")
                        .HasColumnType("datetime2");

                    b.HasKey("RabatId");

                    b.ToTable("Rabatter");

                    b.HasData(
                        new
                        {
                            RabatId = 1001,
                            Aktiv = true,
                            Description = "5% rabat til Bronze-stamkunder",
                            IsKampagne = false,
                            Navn = "Stamkunde Bronze",
                            Percentage = 0.05m,
                            RequiredLoyaltyTier = "Bronze"
                        },
                        new
                        {
                            RabatId = 1002,
                            Aktiv = true,
                            Description = "10% rabat til Sølv-stamkunder",
                            IsKampagne = false,
                            Navn = "Stamkunde Sølv",
                            Percentage = 0.10m,
                            RequiredLoyaltyTier = "Sølv"
                        },
                        new
                        {
                            RabatId = 1003,
                            Aktiv = true,
                            Description = "15% rabat til Guld-stamkunder",
                            IsKampagne = false,
                            Navn = "Stamkunde Guld",
                            Percentage = 0.15m,
                            RequiredLoyaltyTier = "Guld"
                        },
                        new
                        {
                            RabatId = 2001,
                            Aktiv = true,
                            Description = "Julekampagne: 50 kr rabat på alle behandlinger",
                            FixedAmount = 50m,
                            IsKampagne = true,
                            Navn = "Julekampagne",
                            SlutDato = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDato = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Booking", b =>
                {
                    b.HasOne("BellaHair.Domain.Entities.Behandling", "Behandling")
                        .WithMany()
                        .HasForeignKey("BehandlingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BellaHair.Domain.Entities.Kunde", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BellaHair.Domain.Entities.Medarbejder", "Medarbejder")
                        .WithMany()
                        .HasForeignKey("MedarbejderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Behandling");

                    b.Navigation("Kunde");

                    b.Navigation("Medarbejder");
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Faktura", b =>
                {
                    b.HasOne("BellaHair.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BellaHair.Domain.Entities.Kunde", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Kunde");
                });
#pragma warning restore 612, 618
        }
    }
}
