// <auto-generated />
using System;
using BellaHair.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BellaHair.Infrastructure.Migrations
{
    [DbContext(typeof(BellaHairDbContext))]
    partial class BellaHairDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BellaHair.Domain.Entities.Behandling", b =>
                {
                    b.Property<int>("BehandlingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BehandlingId"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VarighedMinutter")
                        .HasColumnType("int");

                    b.HasKey("BehandlingId");

                    b.ToTable("Behandlinger");
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int>("BehandlingId")
                        .HasColumnType("int");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<int>("MedarbejderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValgtRabat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Varighed")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("Bookinger");
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundeId"));

                    b.Property<string>("LoyaltyTier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundeId");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Medarbejder", b =>
                {
                    b.Property<int>("MedarbejderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedarbejderId"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedarbejderId");

                    b.ToTable("Medarbejdere");
                });

            modelBuilder.Entity("BellaHair.Domain.Entities.Rabat", b =>
                {
                    b.Property<int>("RabatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RabatId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RequiredLoyaltyTier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RabatId");

                    b.ToTable("Rabatter");
                });
#pragma warning restore 612, 618
        }
    }
}
